use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://cdn.cocoapods.org/'

platform :ios, '8.0'

target 'TestLib_Example' do
  pod 'TestLib', :path => '../'

  target 'TestLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
